#pragma checksum "..\..\CaptureWindow.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "81DBEC3FFA2C6023F15EDD8DAC1B8905"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace KinectStreams {
    
    
    /// <summary>
    /// CaptureWindow
    /// </summary>
    public partial class CaptureWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 6 "..\..\CaptureWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image camera;
        
        #line default
        #line hidden
        
        
        #line 7 "..\..\CaptureWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Canvas canvas;
        
        #line default
        #line hidden
        
        
        #line 10 "..\..\CaptureWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnColorCam;
        
        #line default
        #line hidden
        
        
        #line 11 "..\..\CaptureWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnStart;
        
        #line default
        #line hidden
        
        
        #line 12 "..\..\CaptureWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnStop;
        
        #line default
        #line hidden
        
        
        #line 13 "..\..\CaptureWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnMenu;
        
        #line default
        #line hidden
        
        
        #line 15 "..\..\CaptureWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton btnLeftArm;
        
        #line default
        #line hidden
        
        
        #line 16 "..\..\CaptureWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton btnRightArm;
        
        #line default
        #line hidden
        
        
        #line 17 "..\..\CaptureWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtUpperToForearmTheta;
        
        #line default
        #line hidden
        
        
        #line 19 "..\..\CaptureWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox RestTimer;
        
        #line default
        #line hidden
        
        
        #line 20 "..\..\CaptureWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtShoulderX;
        
        #line default
        #line hidden
        
        
        #line 21 "..\..\CaptureWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtShoulderY;
        
        #line default
        #line hidden
        
        
        #line 22 "..\..\CaptureWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtElbowX;
        
        #line default
        #line hidden
        
        
        #line 23 "..\..\CaptureWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtElbowY;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/KinectStreams;component/capturewindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\CaptureWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 4 "..\..\CaptureWindow.xaml"
            ((KinectStreams.CaptureWindow)(target)).Loaded += new System.Windows.RoutedEventHandler(this.Window_Loaded);
            
            #line default
            #line hidden
            
            #line 4 "..\..\CaptureWindow.xaml"
            ((KinectStreams.CaptureWindow)(target)).Closed += new System.EventHandler(this.Window_Closed);
            
            #line default
            #line hidden
            return;
            case 2:
            this.camera = ((System.Windows.Controls.Image)(target));
            return;
            case 3:
            this.canvas = ((System.Windows.Controls.Canvas)(target));
            return;
            case 4:
            this.btnColorCam = ((System.Windows.Controls.Button)(target));
            
            #line 10 "..\..\CaptureWindow.xaml"
            this.btnColorCam.Click += new System.Windows.RoutedEventHandler(this.Color_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            this.btnStart = ((System.Windows.Controls.Button)(target));
            
            #line 11 "..\..\CaptureWindow.xaml"
            this.btnStart.Click += new System.Windows.RoutedEventHandler(this.Body_Click);
            
            #line default
            #line hidden
            return;
            case 6:
            this.btnStop = ((System.Windows.Controls.Button)(target));
            
            #line 12 "..\..\CaptureWindow.xaml"
            this.btnStop.Click += new System.Windows.RoutedEventHandler(this.btnStop_Click);
            
            #line default
            #line hidden
            return;
            case 7:
            this.btnMenu = ((System.Windows.Controls.Button)(target));
            
            #line 13 "..\..\CaptureWindow.xaml"
            this.btnMenu.Click += new System.Windows.RoutedEventHandler(this.btnMenu_Click);
            
            #line default
            #line hidden
            return;
            case 8:
            this.btnLeftArm = ((System.Windows.Controls.RadioButton)(target));
            
            #line 15 "..\..\CaptureWindow.xaml"
            this.btnLeftArm.Checked += new System.Windows.RoutedEventHandler(this.btnLeftArm_Checked);
            
            #line default
            #line hidden
            return;
            case 9:
            this.btnRightArm = ((System.Windows.Controls.RadioButton)(target));
            
            #line 16 "..\..\CaptureWindow.xaml"
            this.btnRightArm.Checked += new System.Windows.RoutedEventHandler(this.btnRightArm_Checked);
            
            #line default
            #line hidden
            return;
            case 10:
            this.txtUpperToForearmTheta = ((System.Windows.Controls.TextBox)(target));
            
            #line 17 "..\..\CaptureWindow.xaml"
            this.txtUpperToForearmTheta.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.TextBox_TextChanged);
            
            #line default
            #line hidden
            return;
            case 11:
            this.RestTimer = ((System.Windows.Controls.TextBox)(target));
            return;
            case 12:
            this.txtShoulderX = ((System.Windows.Controls.TextBox)(target));
            return;
            case 13:
            this.txtShoulderY = ((System.Windows.Controls.TextBox)(target));
            return;
            case 14:
            this.txtElbowX = ((System.Windows.Controls.TextBox)(target));
            return;
            case 15:
            this.txtElbowY = ((System.Windows.Controls.TextBox)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

